services:
  postgres:
    image: postgres:17
    container_name: breizhsport-database
    environment:
      POSTGRES_USER: breizhsport
      POSTGRES_PASSWORD: breizhsport
      POSTGRES_DB: breizhsport
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  express:
    build: .
    container_name: breizhsport-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  postgres-data: