name: CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  DB_USER: "db_user"
  DB_PASSWORD: "db_password"
  DB_NAME: "db_name"
  DB_PORT: "5432"
  DB_LOCATION: "localhost"
  API_PORT: "3000"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: breizhsport
          POSTGRES_PASSWORD: breizhsport
          POSTGRES_DB: breizhsport
        ports:
          - "5432:5432"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: |
          npm install

      - name: Launch build process
        run: |
          npm run build