name: CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: breizhsport
          POSTGRES_PASSWORD: breizhsport
          POSTGRES_DB: breizhsport
        ports:
          - "5432:5432"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Shutdown services
        run: |
          docker-compose -f docker-compose.yml down